cdj_acc/cdj_acc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('register.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('book/', include('book.urls')),
    path('entry/', include('entry.urls')),
    path('client/', include('client.urls')),
]

cdj_acc/client/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "client"

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # url(r'^client$', views.register_client, name='register client'),
    # url(r'^registerUser$', views.register_user, name='register_user')
    path('select_client/', views.select_client, name='select_client'),
]

cdj_acc/entry/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "entry"

urlpatterns = [
    path('<slug:acc_name>/borrower=<slug:borrower>', views.get_borrower),
    path('<slug:acc_name>/debtor=<slug:debtor_name>', views.get_debtors),
    path('<slug:acc_name>/', views.transact, name='transaction'),
    path('forms/account_receivable/', views.add_account_receivable, name='add_account_receivable'),
    path('forms/sales/', views.add_sales, name='add_sales'),
    path('forms/payment_to_account_receivable/', views.add_payment_to_account_receivable, name='add_payment_to_account_receivable'),
    path('forms/loans_receivable/', views.add_loans_receivable, name='add_loans_receivable'),
    path('forms/loan_payment/borrower=<slug:borrower>', views.add_loan_payment, name='add_loan_payment'),
    path('forms/loan_payment/borrower=', views.get_404_1),
]

cdj_acc/entry/models.py
from django.db import models
from register.models import Client


class Accounts(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Transactions(models.Model):
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    nameOfTransaction = models.ForeignKey(Accounts, on_delete=models.PROTECT)
    date_entry = models.DateTimeField('Entry Date')

    def __str__(self):
        return str(self.id)+". "+self.nameOfTransaction.name


class AccountReceivable(models.Model):
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    date = models.DateField('Document Date')
    documentNumber = models.PositiveIntegerField()
    buyer = models.CharField(max_length=180)
    cash = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    transaction = models.ForeignKey(Transactions, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.transaction.id)+". "+self.buyer+" "+str(self.cash)


class PaymentToAccountReceivable(models.Model):
    receivable = models.ForeignKey(AccountReceivable, on_delete=models.PROTECT)
    documentNumber = models.PositiveIntegerField()
    date = models.DateField('Document Date')
    cash = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    transaction = models.ForeignKey(Transactions, on_delete=models.CASCADE) 

    def __str__(self):
        return self.receivable.buyer+" cash: "+str(self.cash)


class Sales(models.Model):
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    date = models.DateField('Document Date')
    documentNumber = models.PositiveIntegerField()
    buyer = models.CharField(max_length=180)
    cash = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    transaction = models.ForeignKey(Transactions, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.transaction.id)+". "+self.buyer+" "+str(self.cash)


class CashOnHand(models.Model): 
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    date = models.DateField('Document Date')
    cash = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    transaction = models.ForeignKey(Transactions, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.cash)


class CashInBank(models.Model):
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    date = models.DateField("Document Date")
    cash = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    transaction = models.ForeignKey(Transactions, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.cash)


class LoansReceivable(models.Model):
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    date = models.DateField("Document Date")
    documentNumber = models.PositiveIntegerField()
    firstname = models.CharField(max_length=50)
    middlename = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    amountApplied = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    loanType = models.CharField(max_length=20)
    modeOfPayment = models.CharField(max_length=15)
    termsOfPaymentYear = models.PositiveIntegerField(default=0)
    termsOfPaymentMonth = models.PositiveIntegerField(default=0)
    termsOfPaymentDay = models.PositiveIntegerField(default=0)
    interestRate = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    methodOfInterest = models.CharField(max_length=10)
    serviceFee = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    penaltyRate = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    transaction = models.ForeignKey(Transactions, on_delete=models.CASCADE)

    def __str__(self):
        return self.lastname+", "+self.firstname+" "+str(self.amountApplied)


class ServiceFee(models.Model):
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    date = models.DateField("Document Date")
    cash = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    transaction = models.ForeignKey(Transactions, on_delete=models.CASCADE)

    def __str__(self):
        return self.cash


class LoanPayment(models.Model):
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    loan = models.ForeignKey(LoansReceivable, on_delete=models.CASCADE)
    date = models.DateField("Document Date")
    documentNumber = models.PositiveIntegerField()
    firstname = models.CharField(max_length=50)
    middlename = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    paymentAmount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    transaction = models.ForeignKey(Transactions, on_delete=models.CASCADE)

    def __str__(self):
        return self.lastname+", "+self.firstname+" "+str(self.paymentAmount)

cdj_acc/entry/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.contrib import messages
from entry.models import *
from register.models import Client
from datetime import datetime, timedelta
from django.utils import timezone
from timeit import default_timer
from itertools import chain
from decimal import Decimal

from .forms import AccountReceivableForm, PaymentToAccountReceivableForm, LoansReceivableForm, LoanPaymentForm

#--------------------------------------------------------------------------------------
# HELPER FUNCTIONS

#catch page not found
def get_404_1(request):
    messages.warning(request, "SELECT BORROWER FIRST")
    return redirect("/entry/loan_payment/")

# ADD ALL THE DJANGO FORMS HERE
def append_forms_to_context(context):
    forms = {
        'account_receivable': AccountReceivableForm(auto_id=False),
        'sales': AccountReceivableForm(auto_id=False),
        'payment_to_account_receivable': PaymentToAccountReceivableForm(auto_id=False),
        'loans_receivable': LoansReceivableForm(auto_id=False),
        'loan_payment': LoanPaymentForm(auto_id=False),
    }
    return {**context, **forms}


# GENERATE TEMPLATE FILENAME FROM ACCOUNT NAMES
def generate_filename(list_of_names):
    file_names =[]
    for account in list_of_names:
        file_names+=[account.name.lower().replace(" ","_")+".html"]

    return file_names

# GENERATE DEBTOR TRANSACTIONS
def generate_Btransaction(receivables, buyer_name):
    buyer_payables = receivables.filter(buyer=buyer_name)
    buyer_payments = PaymentToAccountReceivable.objects.filter(
        receivable__client=receivables[0].client, receivable__buyer=buyer_name)
    transactions = sorted(chain(buyer_payables, buyer_payments), key=lambda instance: instance.date)
    transactions2 = []

    balance=0
    for item in transactions:
        temp=[]
        if(item.__class__.__name__=='AccountReceivable'):
            balance+=item.cash
            temp+=[item.date, item.documentNumber, item.cash,'', balance]
        else:
            balance-=item.cash
            temp+=[item.date, item.documentNumber,'', item.cash, balance]
        transactions2+=[temp]
    return transactions2


# GENERATE DEBTOR BALANCE
def get_receivables_balances(receivables):
    debtors = receivables.values('buyer').distinct()
    balances=[]
    for debtor in debtors:
        payables = AccountReceivable.objects.filter(buyer=debtor.get('buyer'))
        payments = PaymentToAccountReceivable.objects.filter(receivable__buyer=debtor.get('buyer'))
        
        debtor_balance=0
        for item in payables:
            debtor_balance+=item.cash
        for item in payments:
            debtor_balance-=item.cash
        balances+=[[debtor.get('buyer'),debtor_balance]]
    return balances

# GET BORROWERS OR LOANEES
def get_loan_borrowers():
    loans = LoansReceivable.objects.all().order_by('lastname').values('firstname','middlename','lastname','loanType').distinct()
    temp = []
    for x in loans:
        x=list(x.values())
        temp+=[[x[0],x[1],x[2],x[3]]]
    return temp


def get_loan_transactions(request, borrower):
    borrower = borrower.split('_')
    # try:
    lr = LoansReceivable.objects.filter(firstname=borrower[0], middlename=borrower[1], lastname=borrower[2], loanType=borrower[3])
    # except(IndexError):
        # messages.warning(request, "BORROWER "+debtor+" DOES NOT EXIST")
        # return redirect('/entry/loan_payment/')        

    lp = LoanPayment.objects.filter(loan=lr[0])

    transactions = sorted( chain(lr,lp), key=lambda instance:instance.date) 

    current_loan=""
    paymentTerms_days=0
    payment_mode=0
    balance=0
    regular_interest_payment=0
    lr_ledger=[]
    dueDate=0
    regular_payment=0
    daily_interest=0
    previous_paymentDate = ""

    for entry in transactions:        
        if(entry.__class__.__name__=='LoansReceivable'):
            
            if(current_loan==""):
                current_loan = entry

            lr_ledger += [  [ entry.date, entry.amountApplied, round(entry.amountApplied-balance-balance*(current_loan.interestRate/100), 2), 0, entry.amountApplied, 0]  ]
            paymentTerms_days = (entry.termsOfPaymentYear*12*30)+(entry.termsOfPaymentMonth*30)+entry.termsOfPaymentDay
            current_loan = entry
            balance = entry.amountApplied
            previous_paymentDate = ""

            if(entry.modeOfPayment=="monthly"):
                payment_mode=30
            elif(entry.modeOfPayment=="semi-monthly"):
                payment_mode=15
            elif(entry.modeOfPayment=="weekly"):
                payment_mode=7
            else:
                payment_mode=1

            dueDate = entry.date+timedelta(days=payment_mode)

            regular_payment = (entry.amountApplied/paymentTerms_days)*payment_mode
            regular_interest_payment = entry.amountApplied*(entry.interestRate/100)*Decimal(payment_mode/360)
            # regular_interest_payment =( (entry.amountApplied*(entry.interestRate/100))/paymentTerms_days )*payment_mode
            daily_interest = entry.amountApplied*(entry.interestRate/100)*Decimal(1/360)
        else:
            if(current_loan.methodOfInterest=='straight'):
                day_advance = (dueDate-entry.date).days
                if(day_advance<0):
                    payment_lapsed = 1+int(day_advance/payment_mode)*-1
                    print("asdf",day_advance,payment_mode,-day_advance%payment_mode)
                    penalty = (payment_lapsed*regular_payment*(current_loan.penaltyRate/100))
                    interest = (-day_advance%payment_mode)*daily_interest+(regular_interest_payment*payment_lapsed)
                else:
                    penalty = 0
                    payment_lapsed = 0
                    interest = (payment_mode-day_advance)*daily_interest+(regular_interest_payment*payment_lapsed)


                #Very advanced payment
                if(interest<0):
                    interest = 0

                deduction_to_principal = entry.paymentAmount-interest-penalty
                if(round(deduction_to_principal,2)==0):
                    deduction_to_principal=0
                balance -= deduction_to_principal
                dueDate+=timedelta(days=payment_mode+payment_mode*payment_lapsed)

                lr_ledger += [  [entry.date, entry.paymentAmount, 0, round(deduction_to_principal, 2), round(balance, 2), round(interest,2), round(penalty, 2)]  ]
                print(entry.date, "", round(deduction_to_principal, 2), round(balance, 2), round(interest,2), round(penalty, 2))
                print(dueDate)
            else:
                daily_interest = balance*(current_loan.interestRate/100)*Decimal(1/360)
                day_advance = (dueDate-entry.date).days
                if(day_advance<0):
                    payment_lapsed = 1+int(day_advance/payment_mode)*-1
                    penalty = (payment_lapsed*regular_payment*(current_loan.penaltyRate/100))
                    interest = (-day_advance%payment_mode)*daily_interest+(daily_interest*payment_mode*payment_lapsed)
                else:
                    penalty = 0
                    payment_lapsed = 0
                    interest = (payment_mode-day_advance)*daily_interest+(daily_interest*payment_mode*payment_lapsed)


                #Very advanced payment
                if(interest<0):
                    interest = 0

                deduction_to_principal = entry.paymentAmount-interest-penalty
                if(round(deduction_to_principal,2)==0):
                    deduction_to_principal=0
                balance -= deduction_to_principal
                dueDate+=timedelta(days=payment_mode+payment_mode*payment_lapsed)

                lr_ledger += [  [entry.date, entry.paymentAmount, 0, round(deduction_to_principal, 2), round(balance, 2), round(interest,2), round(penalty, 2)]  ]
                print(entry.date, "", round(deduction_to_principal, 2), round(balance, 2), round(interest,2), round(penalty, 2))
                print(dueDate)


    return lr_ledger
#--------------------------------------------------------------------------------------

def transact(request, acc_name):
    start = default_timer()
    accounts = get_list_or_404(Accounts)
    my_client = Client.objects.get(pk=1)
    receivables = AccountReceivable.objects.filter(client_id=my_client.id)

    context={
        'acc_name':acc_name,
        'accounts':accounts,
        'template_filenames':generate_filename(accounts),
        'buyer_transactions':[],
        'my_client':my_client,
        'debtor_balances':get_receivables_balances(receivables),
        'loans_list':get_loan_borrowers(),
    }

    context = append_forms_to_context(context)
    print(default_timer()-start)
    return render(request, 'entry/transact.html', context)


def get_borrower(request, acc_name, borrower):
    start = default_timer()
    accounts = get_list_or_404(Accounts)
    my_client = Client.objects.get(pk=1)
    borrower2 = borrower.split("_")
    lr = LoansReceivable.objects.filter(firstname=borrower2[0], middlename=borrower2[1], lastname=borrower2[2], loanType=borrower2[3]).order_by('date')

    context={
        'acc_name':acc_name,
        'accounts':accounts,
        'template_filenames':generate_filename(accounts),
        'loan_transactions':get_loan_transactions(request, borrower),
        'my_client':my_client,
        'loans_list':get_loan_borrowers(),
        'loan': lr[len(lr)-1],
        'borrower':borrower,
    }

    context = append_forms_to_context(context)
    print(default_timer()-start)
    return render(request, 'entry/transact.html', context)


def get_debtors(request, acc_name, debtor_name):
    start = default_timer()
    accounts = get_list_or_404(Accounts)
    my_client = Client.objects.get(pk=1)
    receivables = AccountReceivable.objects.filter(client_id=my_client.id)
    try:

cdj_acc/entry/templates/account_receivable.html
<html>
    <body>

            <form id="account_receivable_form"  action="{% url 'entry:add_account_receivable' %}" method="post" style="display:none;">
                {% csrf_token %}
        
                    <!-- FORMS SECTION -->
                    <div class="form-group">

                        <div class="row">
                            <div class="col-lg-3">
                                Date of transaction
                                {{account_receivable.date}}
                            </div>
                            <div class="col-lg-2">
                                Charge Invoice
                                {{account_receivable.documentNumber}}
                            </div>
                        </div>
            
            
                        <div class="row">
                            <div class="col-lg-12">
                                {{account_receivable.buyer}}
                            </div>
                        </div>
            
                        <div class="row">
                            <div class="col-lg-5">
                                {{account_receivable.cash}}
                            </div>
                        </div>
                     
                        <div class="row">
                            <div class="col-lg-10">
                            </div>

                            <div class="col-lg-2">
                                <button type="submit" class="btn btn-success form-control">
                                    submit
                                </button>
                            </div>
                        </div>
            
                    </div>
       

            </form>

                <!-- The Modal -->
                <div class="modal" id="AReceivable_buyer_names_modal">
                    <div class="modal-dialog">
                        <div class="modal-content">
                    
                            <!-- Modal Header -->
                            <div class="modal-header">
                                <h4 class="modal-title">Name Of Debtors</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                    
                            <!-- Modal body -->
                            <div class="modal-body">

                                <table id="debtors_table2" class="table table-striped table-bordered" style="width:100%;">
                        
                                    <thead>
                                        <tr>
                                            <th>Debtor</th>
                                            <th>Balance</th>
                                        </tr>
                                    </thead>
        
                                    <tbody>
                                        {% for d_balance in debtor_balances %}
                                        <tr>
                                            <td class="select_debtor" data-dismiss="modal">{{ d_balance.0 }}</td>
                                            <td>&#8369;&nbsp;{{ d_balance.1 }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Debtor</th>
                                            <th>Balance</th>
                                        </tr>
                                    </tfoot>
                
                                </table>                        
                
                            </div>
                    
                            <!-- Modal footer -->
                            <div class="modal-footer">
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                            </div>
                    
                        </div>
                    </div>
                </div>

    </body>
</html>

cdj_acc/entry/templates/base.html
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">


        {% load static %}
        <link href="{% static '/css/bootstrap4.min.css' %}" rel="stylesheet">
        <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static '/js/popper.min.js' %}"></script>
        <script src="{% static '/js/bootstrap4.min.js' %}"></script>

        <script src="{% static '/js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static '/js/dataTables.bootstrap4.min.js' %}"></script>
        
        <link href="{% static '/css/style4.css' %}" rel="stylesheet">
        
        <link rel="icon" href="{% static '/img/cdj_emblem.png' %}" type="image/x-icon"/>


        <!-- Font Awesome JS -->
        <script src="{% static '/js/solid.js' %}" ></script>
        <script src="{% static '/js/fontawesome.js' %}"></script>

        <title>
            {% block title %} 
                <!--Title--> 
            {%endblock %}
        </title>

        {% block head %}
            <style>

            </style>
        {% endblock %}
    
    </head>




    <body>
        <!-- Division for NOTIFICATIONS and ALERTS -->
        <div id="notification" style="
            width:30%;
            left:67%;
            top:80%;
            position:absolute;
            height:15%;
            z-index:1;
            ">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}} alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                            {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <div class="wrapper">
            <!-- Sidebar  -->
            <nav id="sidebar">
                <div class="sidebar-header">
                    <!-- Client/Company name here -->
                    <h3 style="text-align:center;">{{my_client.firstname}} {{my_client.middlename}} {{my_client.lastname}}</h3>
                    <strong>CDJ</strong>
                </div>
    
                <ul class="list-unstyled components">
                    <li class="active">
                        <a href="#homeSubmenu" aria-expanded="false">
                            <i class="fas fa-home"></i>
                            Home
                        </a>
                        <!-- <ul class="collapse list-unstyled" id="homeSubmenu">
                            <li>
                                <a href="#">Home 1</a>
                            </li>
                            <li>
                                <a href="#">Home 2</a>
                            </li>
                            <li>
                                <a href="#">Home 3</a>
                            </li>
                        </ul> -->
                    </li>
                    <li>
                        <a href="#">
                            <i class="fas fa-plus-square"></i>
                            Entry
                        </a>

                        <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                            <i class="fas fa-copy"></i>
                            Journals
                        </a>
                        <ul class="collapse list-unstyled" id="pageSubmenu">
                            <li>
                                <a href="#">Cash Receipt</a>
                            </li>
                            <li>
                                <a href="#">Cash Disbursement</a>
                            </li>
                            <li>
                                <a href="#">Sales</a>
                            </li>
                        </ul>

                        <a href="#client" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                            <i class="fas fa-user-circle"></i>
                            Client
                        </a>
                        <ul class="collapse list-unstyled" id="client">
                            <li>
                                <a href="#">Client Profile</a>
                            </li>
                            <li>
                                <a href="{% url 'client:select_client' %}">Select Client</a>
                            </li>
                        </ul>
    
                        <a href="#">
                            <i class="fas fa-briefcase"></i>
                            About
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fas fa-question"></i>
                            FAQ
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fas fa-paper-plane"></i>
                            Contact
                        </a>
                    </li>
                </ul>
    
                <!-- <ul class="list-unstyled CTAs">
                    <li>
                        <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
                    </li>
                    <li>
                        <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
                    </li>
                </ul> -->
            </nav>
    
            <!-- Page Content  -->
            <div id="content">
    
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">
    
                        <button type="button" id="sidebarCollapse" class="btn btn-info">
                            <i class="fas fa-align-left"></i>
                            <!-- <span>Toggle Sidebar</span> -->
                        </button>
                        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fas fa-align-justify"></i>
                        </button>
    
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="nav navbar-nav ml-auto">
                                <li class="nav-item active">
                                    <a class="nav-link" href="#">Page</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Page</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Page</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Page</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>


                <!-- <div class="line"></div> -->

                {% block body %}
                

                {% endblock %} 

            </div>
        </div>
            



        <script type="text/javascript">
            $(document).ready(function () {
                $('#sidebarCollapse').on('click', function () {
                    $('#sidebar').toggleClass('active');
                });
            });
        </script>
    </body>
</html>

cdj_acc/entry/templates/sales.html
<html>

<body>

        <form id="sales_form" action="{% url 'entry:add_sales' %}" method="post" style="display:none;">
            {% csrf_token %}

            <!-- FORMS SECTION -->
            <div class="form-group">
                    
                <div class="row">
                    <div class="col-lg-3">
                        Date of transaction
                        {{sales.date}}
                    </div>
                    <div class="col-lg-2">
                        Charge Invoice
                        {{sales.documentNumber}}
                    </div>
                </div>
    
    
                <div class="row">
                    <div class="col-lg-12">
                        {{sales.buyer}}
                    </div>
                </div>
    
                <div class="row">
                    <div class="col-lg-5">
                        {{sales.cash}}
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg-10">
                    </div>

                    <div class="col-lg-2">
                        <button type="submit" class="btn btn-success form-control">
                            submit
                        </button>
                    </div>
                </div>
        
            </div>
        </form>
</body>

</html>